import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class GeneralService {
  register = {
    employerPortalRegistrationId: 0,
    employerRefNo: '',
    employerName: '',
    businessRegistrationNo: '',
    fircNo: '',
    companyTin: '',
    contactName: '',
    contactPhoneNo: '',
    contactEmailId: '',
    contactFnpfNo: '',
    passportNo: '',
    contactTin: '',
    contactBrn: '',
    statusId: 0,
    statusValue: '',
    businessLicenseNo: '',
    contactTypeId: 0,
    contactTypeValue: '',
    employerPortalUserId: 0,
    employerPortalRegistrationDocument: [],
  };
  userData = {
    portalUserId: 0,
    enableTwoFactor: '',
    maskedEmail: '',
    maskedMobileNo: '',
    isMappedToMultipleOrg: true,
    defaultLandingPageName:'',
    msg: {
      infoMessage: {
        msgID: 0,
        msgType: 0,
        msgDescription: '',
      },
      errorMessage: [
        {
          msgID: 0,
          msgType: 0,
          msgDescription: '',
        },
      ],
      hasError: true,
    },
    lstprotoDefaultLandingPage:[],
    entOrgContact: {
      person: {
        firstName: '',
        middleName: '',
        lastName: '',
        dateOfBirth: '',
        genderId: 0,
        genderValue: '',
        genderDescription: '',
        fatherName: '',
        motherName: '',
        fnpfNo: '',
        tin: '',
        passportNo: '',
        personId: 0,
        mobileNo: '',
        emailId: '',
        citizenshipId: 0,
        citizenshipValue: '',
        citizenshipDescription: '',
        ethnicityId: 0,
        ethnicityValue: '',
        ethnicityDescription: '',
        nationalId: 0,
        nationalValue: '',
        nationalDescription: '',
        maritalStatusId: 0,
        maritalStatusValue: '',
        maritalStatusDescription: '',
        personStatusId: 0,
        personStatusValue: '',
        personStatusDescription: '',
        peopleHubId: 0,
        errorStatusId: 0,
        errorStatusValue: '',
        actionStatusId: 0,
        actionStatusValue: '',
        interfaceStatusId: 0,
        interfaceStatusValue: '',
        hotlistFlag: '',
        suppressWarningsFlag: '',
        duplicateFlag: '',
        cAndFNotificationFlag: '',
        birthRegNo: '',
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: '',
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: '',
            },
          ],
          hasError: true,
        },
      },
      orgRefNo: '',
      orgId: 0,
      contactTypeId: 0,
      contactTypeValue: '',
      contactTypeDescription: '',
      contactStatusId: 0,
      contactStatusValue: '',
      contactStatusDescription: '',
      holdingPercentage: '',
      startDate: '',
      endDate: '',
      emailId: '',
      contactNo: '',
      employerContactId: 0,
      organization: {
        orgId: 0,
        businessName: '',
        tradeName: '',
        orgRefNo: '',
        tin: '',
        businessRegNo: '',
        businessRegDate: '',
        businessLicenseNo: '',
        fircNo: '',
        natureOfBusiness: '',
        orgStatusId: 0,
        orgStatusValue: '',
        orgStatusDescription: '',
        overseasOrg: true,
        lstOrgContact: [null],
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: '',
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: '',
            },
          ],
          hasError: true,
        },
        lstEntAdderss: [
          {
            personId: 0,
            orgId: 0,
            addressId: 0,
            line1: '',
            line2: '',
            city: '',
            province: '',
            island: '',
          },
        ],
        lstEntCommunication: [
          {
            orgCommunicationId: 0,
            orgId: 0,
            orgReFNo: '',
            orgCommunicationTypeId: 0,
            orgCommunicationTypeValue: '',
            orgCommunicationTypeDescription: '',
            orgCommunicationStatusId: 0,
            orgCommunicationStatusValue: '',
            orgCommunicationStatusDescription: '',
            communicationDetail: '',
          },
        ],
      },
      lstprotoentOrganization: [
        {
          orgId: 0,
          businessName: '',
          tradeName: '',
          orgRefNo: '',
          tin: '',
          businessRegNo: '',
          businessRegDate: '',
          businessLicenseNo: '',
          fircNo: '',
          natureOfBusiness: '',
          orgStatusId: 0,
          orgStatusValue: '',
          orgStatusDescription: '',
          overseasOrg: true,
          lstOrgContact: [null],
          msg: {
            infoMessage: {
              msgID: 0,
              msgType: 0,
              msgDescription: '',
            },
            errorMessage: [
              {
                msgID: 0,
                msgType: 0,
                msgDescription: '',
              },
            ],
            hasError: true,
          },
          lstEntAdderss: [
            {
              personId: 0,
              orgId: 0,
              addressId: 0,
              line1: '',
              line2: '',
              city: '',
              province: '',
              island: '',
            },
          ],
          lstEntCommunication: [
            {
              orgCommunicationId: 0,
              orgId: 0,
              orgReFNo: '',
              orgCommunicationTypeId: 0,
              orgCommunicationTypeValue: '',
              orgCommunicationTypeDescription: '',
              orgCommunicationStatusId: 0,
              orgCommunicationStatusValue: '',
              orgCommunicationStatusDescription: '',
              communicationDetail: '',
            },
          ],
        },
      ],
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: '',
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: '',
          },
        ],
        hasError: true,
      },
    },
    currentLoginDate: '',
    lastLoginDate: '',
    token: '',
    passwordExpiredFlag: '',
    resetEmailFlag:'',
    organizationRefNo:'',
    sendOtpToEmail:'',
    sendOtpToMobile:'',
    defaultLandingPage:'',
    totalUnreadMessageCount: 0,
    isbusinessPremisesEditable: false,
    thirdPartyStaffId: '',
    passwordResetFlag: '',
    passwordResetFlagContent: '',
    showNotificationAlertFlag: ''
  };

  login = {
    portalUserId: 0,
    organizationRefNo: '',
  };

  constructor() {}
}
